
`include "controller/uart/raminfr.v"
`include "controller/uart/timescale.v"
`include "controller/uart/uart_debug_if.v"
`include "controller/uart/uart_receiver.v"
`include "controller/uart/uart_regs.v"
`include "controller/uart/uart_rfifo.v"
`include "controller/uart/uart_sync_flops.v"
`include "controller/uart/uart_tfifo.v"
`include "controller/uart/uart_top.v"
`include "controller/uart/uart_transmitter.v"
`include "controller/uart/uart_wb.v"
